#!/usr/bin/env python

import os, sys  # isort:skip

# Add uvicore path to sys.path
uvicore_path = os.path.dirname(os.path.realpath(__file__ + '/../../../'))
if uvicore_path not in sys.path: sys.path.append(uvicore_path)

# Add uvicore/tests/apps path to sys.path
apps_path = os.path.dirname(os.path.realpath(__file__ + '/../'))
if apps_path not in sys.path: sys.path.append(apps_path)

import uvicore  # isort:skip
from app1.package import bootstrap  # isort:skip

# Bootstrap the Uvicore application from the console entrypoint
app = bootstrap.Application(is_console=True)()

if __name__ == '__main__':
    try:
        # Get the cli method from the IoC
        cli = uvicore.ioc.make('Console')

        # Instantiate the main asyncclick group
        cli(_anyio_backend='asyncio')

    except KeyboardInterrupt:
        try:
            sys.exit(0)
        except SystemExit:
            os._exit(0)
