#!/usr/bin/env python

# Add uvicore/tests/apps path to sys.path
import os, sys  # isort:skip
apps_path = os.path.dirname(os.path.realpath(__file__ + '/../'))
if apps_path not in sys.path: sys.path.append(apps_path)

import uvicore  # isort:skip
from app1.services import bootstrap  # isort:skip
from uvicore.support.dumper import dump, dd  # isort:skip

# Bootstrap the Uvicore application
app = bootstrap.application(is_console=True)

# Initialize CLI
if __name__ == '__main__':
    # Run the main click group by executing the actual method in the Ioc
    cli = uvicore.ioc.make('Console')
    cli(_anyio_backend='asyncio')
